Fix for changeState Event in loop
aclonegeek/SSM pull request #4
Opened 2019-05-14 07:17 UTC by maximaexchen

Please review. I am not a pro with github.
I hope its ok like this.

2019-05-16 00:55 UTC, aclonegeek requested changes
Looks good! Do you mind also replacing `break` with `return` in these places?

[Here](https://github.com/aclonegeek/SSM/blob/fcf0623bffee483d86aff1f587b8d0db37f72ce9/src/MenuState.cpp#L41), [here](https://github.com/aclonegeek/SSM/blob/fcf0623bffee483d86aff1f587b8d0db37f72ce9/src/GameState.cpp#L30), and finally, [here](https://github.com/aclonegeek/SSM/blob/fcf0623bffee483d86aff1f587b8d0db37f72ce9/src/GameState.cpp#L35).

Thanks!

2019-05-16 23:43 UTC, aclonegeek approved these changes

2019-05-16 23:44 UTC, aclonegeek commented
Awesome! Thanks a bunch :smile:.

2019-05-16 23:44 UTC, merged

2019-05-17 07:07 UTC, maximaexchen commented
Your welcome. Thanks for sharing. 👍